## Pandas - Importing data

Please download the following data and move it to an appropriate folder:

- <a href="https://drive.google.com/file/d/1gVDDJg3Ngnz8h9f2pX9AcdgWgx5zkV6U/view?usp=sharing">Bridge Inspections excerpt</a>.

In [1]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

In [3]:
## import data and store in dataframe call dfbi (short perhaps for dataframe bridge inspections)
dfbi = pd.read_csv("bridge-inspections-excerpt.csv")

dfbi

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [4]:
## call the first 10 rows
dfbi.head(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN
7,47,189,'GOOSE CREEK',36033059.0,86040120.0,2.0,8.0,1965.0,2,19.0,N,N,N,6,6,NaN
8,47,189,'BRANCH',36014830.0,86030353.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,6,NaN
9,47,189,'PURTLE CREEK',36004548.0,86023480.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,6,NaN

In [5]:
## call the last 5 rows
dfbi.tail(5)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [6]:
## call a 20 random rows
dfbi.sample(20)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
92809,51,710,'Berkley Ave & Ramp',36495281.0,76171085.0,NaN,16.0,1988.0,4,2.0,NaN,NaN,NaN,NaN,NaN,NaN
19512,48,309,'WILLIAMS CRK #2044',31374502.0,96581070.0,2.0,9.0,1974.0,5,0.0,7,7,6,6,N,NaN
35775,48,491,'SOWES BRANCH TRIB #1',30400303.0,97502422.0,2.0,6.0,2006.0,5,2.0,8,7,6,7,N,NaN
27727,48,201,'HCFCD DITCH',29364217.0,95164217.0,4.0,17.0,1963.0,2,1.0,7,7,7,7,N,NaN
85847,51,710,'Holt St & Light Rail',36504052.0,76164098.0,1.0,11.0,1990.0,5,2.0,7,6,7,8,N,NaN
40828,48,273,'FM 1356',27292819.0,97504827.0,1.0,14.0,2000.0,5,2.0,6,7,6,N,N,NaN
46926,48,113,'BNSF RR',32543308.0,96423102.0,4.0,14.0,1955.0,1,2.0,7,7,7,N,N,NaN
46870,48,113,'DRAINAGE DITCH',32542980.0,96532774.0,4.0,19.0,1969.0,1,19.0,N,N,N,8,7,NaN
95569,53,15,'3RD AVE / SR 411',46072296.0,122553568.0,1.0,12.0,1961.0,2,5.0,7,7,7,N,N,NaN
91208,51,5,'RTE 42',37495504.0,79454303.0,NaN,6.0,1978.0,3,2.0,NaN,NaN,NaN,NaN,NaN,NaN
17928,48,145,'BR OF BIG SANDY CRK',31185576.0,96494915.0,1.0,6.0,1949.0,1,19.0,N,N,N,7,6,NaN
25140,48,201,'COLLINGSWORTH ST',29473797.0,95202186.0,1.0,12.0,1997.0,5,2.0,7,7,7,N,N,NaN
6431,48,363,'TRIB. TO BARTON CREEK',32305153.0,98220328.0,1.0,7.0,1970.0,1,19.0,N,N,N,7,7,NaN
14652,48,413,'DRAW',30533722.0,100534916.0,1.0,6.0,1969.0,1,19.0,N,N,N,7,7,NaN
46991,48,113,'TURTLE CREEK',32474668.0,96492661.0,4.0,14.0,1973.0,1,2.0,6,6,6,6,N,NaN
79704,51,59,'BRANCH OF ACCOTINK CREEK',38500541.0,77130323.0,1.0,11.0,1962.0,1,19.0,N,N,N,6,6,NaN
35211,48,491,'DRAIN',30381769.0,97260985.0,1.0,6.0,1941.0,1,19.0,N,N,N,7,6,NaN
8088,48,439,'VILLAGE CREEK',32432187.0,97110477.0,1.0,14.0,1958.0,1,2.0,6,6,6,6,N,NaN
98130,53,57,'FINNEY CREEK',48252443.0,121454641.0,64.0,9.0,2005.0,3,2.0,7,7,7,8,N,NaN
22568,48,407,'HUFFMAN CREEK',30323687.0,95014283.0,1.0,7.0,1997.0,5,0.0,8,8,7,7,N,NaN

In [7]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there

dfbi.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   STATE_CODE_001           100000 non-null  int64
 1   COUNTY_CODE_003          100000 non-null  int64
 2   FEATURES_DESC_006A       100000 non-null  str
 3   LAT_016                  99493 non-null   float64
 4   LONG_017                 99486 non-null   float64
 5   OWNER_022                82621 non-null   float64
 6   FUNCTIONAL_CLASS_026     99660 non-null   float64
 7   YEAR_BUILT_027           99997 non-null   float64
 8   STRUCTURE_KIND_043A      100000 non-null  int64
 9   STRUCTURE_TYPE_043B      99999 non-null   float64
 10  DECK_COND_058            82621 non-null   str
 11  SUPERSTRUCTURE_COND_059  82621 non-null   str
 12  SUBSTRUCTURE_COND_060    82621 non-null   str
 13  CHANNEL_COND_061         82621 non-null   str
 14  CULVERT_COND_062         82621 non-null   str
 15  PIER_PROTECTION_111      4353 non-null    float64
dtypes: float64(7), int64(3), str(6)
memory usage: 12.2 MB

### Which column has the most missing data...just a quick estimate?

In [9]:
print("column 15")

column 15

In [10]:
## call the top 7 rows
dfbi.head(7)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN

In [11]:
## call a sample of 10
dfbi.sample(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
32002,48,481,'BRITT BRANCH',29301590.0,96041139.0,1.0,7.0,1969.0,1,19.0,N,N,N,7,7,NaN
20562,48,401,'BILLY DITCH',32012770.0,94365472.0,1.0,7.0,1937.0,1,19.0,N,N,N,5,6,NaN
42113,48,41,'FM 60',30365667.0,96205484.0,1.0,14.0,1967.0,1,2.0,6,6,7,N,N,NaN
21882,48,225,'BIG ELKHART CREEK',31291709.0,95351157.0,2.0,9.0,2018.0,5,1.0,8,8,8,7,N,NaN
50838,48,37,'BOOTHE CREEK',33214375.0,94414000.0,1.0,2.0,1960.0,1,19.0,N,N,N,7,6,NaN
82580,51,139,'MILL CREEK',38392509.0,78304406.0,1.0,2.0,1951.0,1,19.0,N,N,N,8,6,NaN
43833,48,477,'SHIRTTAIL BRANCH',30064880.0,96240800.0,2.0,9.0,2013.0,3,2.0,7,6,6,6,N,NaN
94754,53,27,'HOQUIAM RIVER',46583132.0,123522402.0,1.0,14.0,1928.0,3,16.0,5,4,6,5,N,3.0
35935,48,491,'DRAINAGE DITCH',30310578.0,97371960.0,4.0,19.0,2014.0,1,19.0,N,N,N,6,7,NaN
83965,51,167,'CASTLE RUN CREEK',36512951.0,82190006.0,1.0,9.0,1970.0,1,1.0,7,7,7,6,N,NaN

In [12]:
## call the bottom 6
dfbi.tail(6)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99994,53,61,'SWAMP CREEK',47482979.0,122152176.0,2.0,16.0,1963.0,1,22.0,7,7,5,6,N,NaN
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [14]:
## call the year built column using dot notation
dfbi.YEAR_BUILT_027

0        1965.0
1        1930.0
2        1935.0
3        1960.0
4        1970.0
          ...
99995    1956.0
99996    1960.0
99997    1965.0
99998    1981.0
99999    1963.0
Name: YEAR_BUILT_027, Length: 100000, dtype: float64

In [16]:
## call FEATURES_DESC_006A as a series using square bracket notation
dfbi["FEATURES_DESC_006A"]

0                          'BRANCH'
1                          'BRANCH'
2                          'BRANCH'
3                        'OVERFLOW'
4                 'HURRICANE CREEK'
                    ...
99995                 'TROUT CREEK'
99996              'COLVILLE RIVER'
99997                       'DRAIN'
99998                 'LEACH CREEK'
99999    'SOUTH FORK PALOUSE RIVER'
Name: FEATURES_DESC_006A, Length: 100000, dtype: str

In [22]:
## what are the unique owner codes?
dfbi.OWNER_022.unique()

array([ 2.,  4.,  1.,  3., 79., 63., 67., 64., 70., 66., 72., 74., nan,
       68., 21., 80., 31., 32., 11., 40., 25., 26., 75., 12., 27., 55.,
       56., 69., 62., 73., 76., 54., 77.])

### What do these codes mean?

In [25]:
print("I dont know, maybe they are connected to another database?")

I dont know, maybe they are connected to another database?